name: 🤖 Welcome Bot

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: 🤗 Welcome First-Time Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            🎉 Hey @${{ github.actor }}! Thanks for opening your **first issue** in this repo.  
            We're glad you're here! Make sure to review our [Contributing Guide](CONTRIBUTING.md) to get started. 🚀

          pr-message: |
            👏 Hello @${{ github.actor }}! Welcome to your **first pull request** in this project!  
            Thanks for contributing. We’ll review this shortly. Don’t forget to check our [Code of Conduct](CODE_OF_CONDUCT.md) and [Contribution Guidelines](CONTRIBUTING.md). 💙
