name: "Auto Label Pull Request"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on file changes
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
