name: PR Review Bot

on:
  pull_request:
    types: [opened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto review comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Hello @${{ github.actor }}!\n\n` +
                    `Thanks for opening this pull request. Please make sure you've done the following:\n\n` +
                    `✅ Described what your PR does\n` +
                    `✅ Linked any related issues\n` +
                    `✅ Followed naming and formatting guidelines\n\n` +
                    `Our team will review your contribution soon! 🚀`
            })
